# Site settings
title: Kestrel
email: tom@kestreloutdoors.co.uk
description: >
  Mountain walking with a qualified mountain leader in the Lake District & Snowdonia National Parks
  Whether you are looking for a gentle introduction to hillwalking or a hike in more challenging terrain,
  Kestrel would love to share the enjoyment of a mountain adventure with you.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kestreloutdoors.co.uk" # the base hostname & protocol for your site

# Banner
banner_strapline: Unlock Adventure
banner_subtitle: "Experience the beauty of Britain’s national parks with Kestrel"
call_to_action_button_text: Book Now
call_to_action_button_link: /booking/

# Build settings
markdown: kramdown

# Site variables
site_designer: Huw Diprose
site_designer_website: http://www.huwdiprose.co.uk
